language: rust
rust:
  - nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenexr-dev
script:
  - cargo build --verbose --all --no-default-features
  - cargo test --verbose --all --no-default-features
