image: jimmycuadra/rust

pipelines:
  branches:
    master:
      - step:
          script:
            - echo "Build project"; cargo build --release
            - echo "Running tests"; cargo test --release