image: rust:latest

pipelines:
  default:
    - step:
        script:
          - echo "Build project"; cargo build --release --no-default-features
          - echo "Running tests"; cargo test --release --no-default-features
