[package]
name = "rustracer-core"
version = "0.1.0"
authors = ["Antoine Büsch <antoine.busch@gmail.com>"]

[features]
default = ["exr"]
display = ["minifb"]
exr = ["openexr"]

[dependencies]
approx = "0.3"
atomic = "0.4"
bitflags = "1"
byteorder = "1.2"
chrono = "0.4"
combine = "2"
crossbeam = "0.7"
failure = "0.1"
image = "0.22"
indicatif = "0.11"
itertools = "0.8"
lazy_static = "1.3"
light_arena = "1.0.1"
log = "0.4"
minifb = { version = "0.12", optional = true }
ndarray = "0.12"
ndarray-parallel = "0.9"
num = "0.2"
num_cpus = "1"
openexr = { version = "0.7", optional = true }
parking_lot = "0.9"
ply-rs = "0.1"
rayon = "1"
state = { version = "0.4", features = ["tls"]}
thread-id = "3"

[dev-dependencies]
rand = "0.7"
quickcheck = "0.8"
