[package]
name = "rustracer-core"
version = "0.1.0"
authors = ["Antoine Büsch <antoine.busch@gmail.com>"]

[features]
default = ["exr"]
display = ["minifb"]
exr = ["openexr"]

[dependencies]
approx = "0.3"
atomic = "0.4"
bitflags = "1"
byteorder = "1.2"
chrono = "0.4"
combine = "2"
crossbeam = "0.3"
failure = "0.1"
image = "0.19"
indicatif = "0.9"
itertools = "0.7"
lazy_static = "1.0"
light_arena = {git = "https://github.com/abusch/light_arena", branch="remove_placement_syntax"}
log = "0.4"
minifb = { version = "0.10", optional = true }
ndarray = "0.11"
ndarray-parallel = "0.8"
num = "0.2"
num_cpus = "1"
openexr = { version = "0.6", optional = true }
parking_lot = {version = "0.6"}
# ply-rs = "0.1"
ply-rs = { git = "https://github.com/abusch/ply-rs/" }
rayon = "1"
state = { version = "0.4", features = ["tls"]}
thread-id = "3"

[dev-dependencies]
rand = "0.5"
quickcheck = "0.6"
