[package]
name = "rustracer"
version = "0.1.0"
authors = ["Antoine Büsch <antoine.busch@gmail.com>"]
edition = "2018"

[dependencies]
rustracer-core = { path = "../rustracer-core/"}
clap = "2"
failure = "0.1"
indicatif = "0.14"
log = "0.4"
flexi_logger = "0.15"
num_cpus = "1"
