[package]
name = "rustracer"
version = "0.1.0"
authors = ["Antoine Büsch <antoine.busch@gmail.com>"]
edition = "2018"

[dependencies]
rustracer-core = { path = "../rustracer-core/"}
anyhow = "1"
clap = "2"
indicatif = "0.16"
log = "0.4"
flexi_logger = "0.18"
num_cpus = "1"
